// Este módulo contiene los datos de los productos, datosProductos.js
const productosAbarrotes = [
    "Coca-Cola 600ml", "Pepsi 1L", "Fanta 500ml", "Sprite 2L", "Jugo Del Valle 1L",
    "Leche Lala 1L", "Huevo San Juan 30pz", "Pan Bimbo Grande", "Tortillas 1kg",
    "Arroz SOS 1kg", "Frijol La Costeña 500g", "Aceite Capullo 1L", "Azúcar Zulka 1kg",
    "Sal La Fina 500g", "Café Nescafé 200g", "Atún Dolores 140g", "Sardina Herdez 120g",
    "Sopa Maruchan Camarón", "Galletas Gamesa Vainilla", "Chocolate Abuelita 1kg",
    "Maseca 2kg", "Harina Robin Hood 1kg", "Avena Quaker 500g", "Cereal Zucaritas 500g",
    "Papas Sabritas 100g", "Jumex Mango 1L", "Agua Bonafont 1L", "Yoplait Fresa 1L",
    "Queso Philadelphia 250g", "Mantequilla Lala 200g", "Jamón Fud 250g",
    "Salchicha San Rafael 500g", "Cerveza Corona 355ml", "Vino Gato Negro 750ml",
    "Whisky Buchanan's 1L", "Vodka Smirnoff 750ml", "Cloro Pinol 1L", "Jabón Zote 400g",
    "Detergente Ariel 1kg", "Suavitel 1L", "Papel Higiénico Regio 4pz",
    "Toallas Scott 100pz", "Pasta Dental Colgate 100g", "Jabón Dove 90g",
    "Shampoo Head & Shoulders 400ml", "Desodorante Axe 150ml", "Pañales Huggies 50pz",
    "Leche en polvo Nido 400g", "Catsup Heinz 500g", "Mostaza French's 200g",
    "Mayonesa McCormick 250g", "Salsa Valentina 200ml", "Chiles La Costeña 100g",
    "Enlatados La Sierra 400g", "Conservas Herdez 300g", "Miel Karo 500g",
    "Mermelada Smucker's 250g", "Cajeta Coronado 300g", "Nestlé Media Crema 250g",
    "Leche Condensada La Lechera 390g", "Chocolate en polvo Nesquik 500g",
    "Cereal Corn Flakes 500g", "Aceitunas La Española 200g", "Vinagre Heinz 500ml",
    "Salsa Inglesa 150ml", "Salsa Soya 250ml", "Pimienta McCormick 50g",
    "Canela Molida 100g", "Clavo Molido 50g", "Comino Molido 50g", "Orégano Seco 50g",
    "Ajo en polvo 50g", "Cebolla en polvo 50g", "Chile en polvo 50g", "Maicena 200g",
    "Polvo para hornear 100g", "Vainilla McCormick 100ml", "Colorante Vegetal 50ml",
    "Levadura Seca 50g", "Gelatina D'Gari 100g", "Flan Royal 100g", "Café Instantáneo 100g",
    "Té Lipton 100g", "Manzanilla 50g", "Hierbabuena 50g", "Té Verde 50g",
    "Chocolate Hershey's 100g", "Cacahuates Japoneses 200g", "Palomitas Act II 100g",
    "Churrumais 100g", "Rufles Queso 100g", "Doritos Nacho 100g", "Cheetos Torciditos 100g",
    "Tostitos 100g", "Oreo 150g", "Emperador Chocolate 150g", "Gansito 50g",
    "Pinguinos 50g", "Submarinos 50g", "Mantecadas 50g", "Nito 50g", "Chocorroles 50g",
    "Coca-Cola Light 600ml", "Pepsi Light 1L", "Fanta Zero 500ml", "Sprite Zero 2L",
    "Jugo Del Valle Light 1L", "Leche Lala Light 1L", "Yoplait Light 1L",
    "Queso Philadelphia Light 250g", "Mantequilla Lala Light 200g", "Jamón Fud Light 250g",
    "Salchicha San Rafael Light 500g", "Cerveza Corona Light 355ml", "Vino Gato Light 750ml",
    "Whisky Buchanan's Light 1L", "Vodka Smirnoff Light 750ml", "Agua Bonafont Light 1L",
    "Galletas Gamesa Light 200g", "Chocolate Abuelita Light 1kg", "Avena Quaker Light 500g",
    "Cereal Zucaritas Light 500g", "Leche en polvo Nido Light 400g", "Catsup Heinz Light 500g",
    "Mayonesa McCormick Light 250g", "Salsa Valentina Light 200ml", "Miel Karo Light 500g",
    "Mermelada Smucker's Light 250g", "Cajeta Coronado Light 300g", "Nestlé Light 250g",
    "Leche Condensada Light 390g", "Chocolate en polvo Light 500g", "Cereal Corn Flakes Light 500g",
    "Chiles Secos La Costeña 100g", "Sopa Knorr 100g", "Puré de Tomate La Costeña 250g",
    "Champiñones La Costeña 200g", "Elote Enlatado La Costeña 220g", "Chiles Chipotles La Costeña 100g",
    "Leche en Polvo Klim 400g", "Café de Olla 200g", "Té Manzanilla Relax 50g",
    "Miel de Abeja 500g", "Avena Quaker Miel 500g", "Galletas Marias Gamesa 500g",
    "Cacahuates Enchilados 200g", "Paletas de Cajeta 50g", "Pulpa de Tamarindo 200g",
    "Agua Mineral Epura 1L", "Jugo Clamato 1L"
  ];
  
  module.exports = productosAbarrotes;